---
vim_plugin_dir: '{{ ansible_env.HOME }}/.vim'
rfvim_reinstall: false
j2vim_reinstall: false
j2vim:
    git:
        proto: 'https'
        host: 'github.com'
        user: 'Glench'
        repo:
            name: 'Vim-Jinja2-Syntax'
            version: 'master'
        directory: '/tmp'
rfvim:
    git:
        proto: 'https'
        host: 'github.com'
        user: 'mfukar'
        repo:
            name: 'robotframework-vim'
            version: 'master'
        directory: '/tmp'
...
