---

- name: 'Ansible Extras | Variables'
  include_vars: 'vars/ansible_extras.yaml'

- name: 'PIP | Tasks'
  include_tasks: 'tasks/pip.yaml'
  when: 'ansible_extras_install | bool'

- name: 'Ansible Extras | Install python packages'
  pip:
    name: '{{ item.name | default(item) }}'
    version: '{{ item.version | default("omit") }}'
    chdir: '{{ ansible_env.HOME }}'
    extra_args: '--user'
    state: '{{ item.state | default("present") }}'
    executable: '{{ pip_executable }}'
  environment:
    PIP_CONFIG_FILE: '{{ ansible_env.HOME }}/.pip.conf'
    PYTHONWARNINGS: 'ignore:Unverified HTTPS request'
  loop: '{{ ansible_extras_pip_packages }}'
  when: 'ansible_extras_install | bool'

- name: 'Ansible Extras | Install system packages'
  apt:
    name: '{{ item }}'
    state: 'present'
    force_apt_get: 'yes'
    install_recommends: 'no'
  become: 'yes'
  loop: '{{ ansible_extras_system_packages }}'
  when: 'ansible_extras_install | bool'
...
