---

- name: 'BASH profile | Variables'
  include_vars: 'vars/bash_profile.yaml'

- name: 'BASH profile | Ensure file exists'
  copy:
    content: ''
    dest: '{{ bash_profile_path }}'
    owner: '{{ ansible_env.USER }}'
    group: '{{ ansible_env.USER }}'
    force: 'no'
    mode: 0644

- name: 'BASH profile | Parse Git branch and Add brackets'
  blockinfile:
    path: '{{ bash_profile_path }}'
    marker: '# {mark} ANSIBLE MANAGED BLOCK git_command_prompt'
    state: 'present'
    block: |
      parse_git_branch_and_add_brackets() {
          git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\ \[\1\]/'
      }

- name: 'BASH profile | PIP Bash completion'
  blockinfile:
    path: '{{ bash_profile_path }}'
    marker: '# {mark} ANSIBLE MANAGED BLOCK pip_completion'
    state: 'present'
    block: |
      pip_completion() {
          COMPREPLY=( $( COMP_WORDS="${COMP_WORDS[*]}" \
          COMP_CWORD=$COMP_CWORD \
          PIP_AUTO_COMPLETE=1 $1 ) )
      }
      complete -o default -F pip_completion pip

- name: 'BASH profile | Set global PATH so it includes user private ~/bin'
  blockinfile:
    path: '{{ bash_profile_path }}'
    marker: '# {mark} ANSIBLE MANAGED BLOCK user private ~/bin'
    state: 'present'
    block: |
      if [ -d "$HOME/bin" ]; then
          PATH="$HOME/bin:$PATH"
      fi

- name: 'BASH profile | Set global PATH to include user ~/.local/bin'
  blockinfile:
    path: '{{ bash_profile_path }}'
    marker: '# {mark} ANSIBLE MANAGED BLOCK PATH ~/.local/bin'
    state: 'present'
    block: |
      if [ -d "$HOME/.local/bin" ]; then
          PATH="$HOME/.local/bin:$PATH"
      fi

- name: 'BASH profile | Source .bash_aliases file if exists'
  blockinfile:
    path: '{{ bash_profile_path }}'
    marker: '# {mark} ANSIBLE MANAGED BLOCK ~/.bash_aliases'
    state: 'present'
    block: |
      if [ -f ~/.bash_aliases ]; then
          . ~/.bash_aliases
      fi

- name: 'BASH profile | Add user ENV variables'
  lineinfile:
    dest: '{{ bash_profile_path }}'
    state: 'present'
    line: 'export {{ item.name }}="{{ item.value }}"'
    regexp: '^export {{ item.name }}='
  loop: '{{ bash_profile_env_vars }}'

- name: 'BASH profile | Set global PATH to include user installed rubygems'
  blockinfile:
    path: '{{ bash_profile_path }}'
    marker: '# {mark} ANSIBLE MANAGED BLOCK ~/.gem/ruby'
    state: 'present'
    block: |
      if which ruby >/dev/null && which gem >/dev/null; then
          PATH="$(ruby -e 'puts Gem.user_dir')/bin:$PATH"
      fi

- name: 'BASH Profile | Vault Bash Completion'
  blockinfile:
    path: '{{ bash_profile_path }}'
    marker: '# {mark} ANSIBLE MANAGED BLOCK vault completion'
    state: 'present'
    block: |
      if which vault > /dev/null; then
          complete -C $(which vault) vault
      fi

- name: 'BASH Profile | Set global PATH to include Go binary'
  blockinfile:
    path: '{{ bash_profile_path }}'
    marker: '# {mark} ANSIBLE MANAGED BLOCK PATH /usr/local/go/bin/go'
    state: 'present'
    block: |
      if [ -d "/usr/local/go/bin" ]; then
          PATH="/usr/local/go/bin:$PATH"
      fi

- name: 'BASH Profile | Kubectl Bash completion'
  blockinfile:
    path: '{{ bash_profile_path }}'
    marker: '# {mark} ANSIBLE MANAGED BLOCK kubectl completion'
    state: 'present'
    block: |
      source <(kubectl completion bash)
...
