---

- name: 'Go | Variables'
  include_vars: 'vars/go.yaml'

- name: 'Go | Check if is already installed'
  stat:
    path: '/usr/local/go/bin/go'
  register: 'go_check_existing'

- name: 'Go | Download tarball'
  become: 'yes'
  get_url:
    url: '{{ go_download_url }}'
    dest: '{{ go_src_tarball }}'
    checksum: 'sha256:{{ go_checksum }}'
  when: 'not go_check_existing.stat.exists'

- name: 'Go | Extract tarball'
  become: 'yes'
  unarchive:
    src: '{{ go_src_tarball }}'
    dest: '/usr/local'
    copy: 'no'
  when: 'not go_check_existing.stat.exists'

- name: 'Go | Get version'
  shell: '/usr/local/go/bin/go version'
  register: 'go_version_result'
  changed_when: false

- name: 'Go | Show version'
  debug:
    var: 'go_version_result.stdout'
...
