---

- name: 'Git | Repositories variables'
  include_vars: 'vars/repos.yaml'

- name: 'Git | Clone repositories'
  git:
    repo: '{{ item.src }}'
    dest: '{{ item.dest }}/{{ item.name }}'
    version: '{{ item.version }}'
    accept_hostkey: 'yes'
    update: '{{ item.pull }}'
    remote: '{{ item.remote }}'
  loop: '{{ repositories }}'
...
