---

- name: 'Ruby | Variables'
  include_vars: 'vars/ruby.yaml'

- name: 'Ruby | Install dependencies'
  apt:
    name: '{{ ruby_dependencies }}'
    state: 'present'
    force_apt_get: 'yes'
    install_recommends: 'no'
  become: 'yes'

- name: 'Ruby | Install bundler:{{ ruby_bundler_version }}'
  gem:
    name: 'bundler'
    state: 'present'
    version: '{{ ruby_bundler_version }}'
    user_install: 'yes'
  when: 'ruby_install_bundler | bool'

- name: 'Ruby | Install user configured gems'
  gem:
    name: '{{ item.name | default("item") }}'
    version: '{{ item.version | default("omit") }}'
    state: '{{ item.state | default("present") }}'
    user_install: 'yes'
  loop: '{{ ruby_install_user_gems }}'

- name: 'Ruby | Verify installation'
  shell: 'ruby --version'
  changed_when: false
  register: 'ruby_version'

- name: 'Ruby | Show version'
  debug:
    var: 'ruby_version.stdout'
...
