---

- name: 'PIP | Tasks'
  include_tasks: 'tasks/pip.yaml'

- name: 'Tox | Variables'
  include_vars: 'vars/tox.yaml'

- name: 'Tox | Install automation tool'
  pip:
    name: '{{ item.name | default(item) }}'
    version: '{{ item.version | default("omit") }}'
    chdir: ' {{ ansible_env.HOME }}'
    extra_args: '--user'
    state: '{{ item.state | default("present") }}'
    executable: '{{ pip_executable }}'
  environment:
    PIP_CONFIG_FILE: '{{ ansible_env.HOME }}/pip.conf'
    PYTHONWARNINGS: 'ignore:Unverified HTTPS request'
  loop: '{{ tox_pip_dependencies }}'

- name: 'Tox | Verify installation'
  shell: 'python -m tox --version'
  changed_when: false
  register: 'tox_version_result'

- name: 'Tox | Show version'
  debug:
    var: 'tox_version_result.stdout'
...
