---

version: 2
updates:
  - package-ecosystem: 'pip'
    directory: '/requirements.d'
    schedule:
      interval: 'daily'
    labels:
      - 'enhancement'
      - 'dependabot'
    ignore:
      - dependency-name: 'shellcheck'
  - package-ecosystem: 'bundler'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'enhancement'
      - 'dependabot'
...
