---

version: 2
updates:
  - package-ecosystem: 'pip'
    directory: '/requirements.d'
    schedule:
      interval: 'daily'
    labels:
      - 'enhancement'
      - 'dependabot'
    ignore:
      - dependency-name: 'shellcheck'
          - '==0.8.0.3'
      - dependency-name: 'pymdown-extensions'
        versions:
          - '==9.1'
      - dependency-name: 'ansible-lint[community]'
        versions:
          - '>5.4.0'
  - package-ecosystem: 'bundler'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'enhancement'
      - 'dependabot'
...
