---

version: 2
updates:
  - package-ecosystem: 'pip'
    directory: '/requirements.d'
    schedule:
      interval: 'daily'
    labels:
      - 'enhancement'
      - 'dependabot'
    ignore:
      - dependency-name: 'shellcheck'
      - dependency-name: 'pymdown-extensions'
      - dependency-name: 'Pygments'
        versions:
          - '>2.11.2'
      - dependency-name: 'ansible-lint[community]'
        versions:
          - '>5.4.0'
      - dependency-name: 'jinja2'
  - package-ecosystem: 'bundler'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'enhancement'
      - 'dependabot'
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'daily'
...
