---
- name: 'Check for installed yq version'
  shell: "{{ yq_install_dir }}/yq --version"
  args:
    executable: '/bin/bash'
  failed_when: false
  changed_when: false
  register: 'yq_show_version'

- name: 'Define installed yq version'
  set_fact:
    yq_installed_version: '{{ yq_show_version.stdout | default("") | regex_search(version_re) }}'
  vars:
    version_re: '(?:\d{1,}\.){2}\d{1,}'

- name: 'Verify installed yq version'
  assert:
    that:
      - 'yq_installed_version == yq_version'
    fail_msg: 'yq installation failed, {{ yq_version }} != {{ yq_installed_version }}'
    success_msg: 'Installed yq version is: {{ yq_version }}'
...
