---

dist: focal
language: generic
python:
    - '3.8'
addons:
    apt:
        update: true
install:
    - pip install --user --upgrade pip==22.0.4
    - pip install --user tox==3.24.5
before_script:
    - pip --version
    - tox --version
script: tox -e py3,linters
notifications:
    email:
        on_success: change
        on_failure: always
...
