---
- name: 'Adding BASH aliases'
  lineinfile:
    dest: '{{ bash_aliases_path }}'
    state: 'present'
    create: 'yes'
    mode: 0644
    owner: '{{ ansible_env.USER }}'
    group: '{{ ansible_env.USER }}'
    line: 'alias {{ item.alias }}="{{ item.command }}"'
    regexp: '^alias {{ item.alias }}='
  loop: '{{ bash_aliases }}'
...
