---
- name: 'Import PIP role'
  import_role:
    name: 'python/pip'

- name: 'Install Kube-shell (kubernetes integrated shell)'
  pip:
    name: '{{ kubeshell_package_name }}'
    version: '{{ kubeshell_package_version | default("omit") }}'
    chdir: ' {{ ansible_env.HOME }}'
    extra_args: '{{ kubeshell_package_extra_args | default("omit") }}'
    state: 'present'
    executable: '{{ pip_executable }}'
  environment:
    PIP_CONFIG_FILE: '{{ ansible_env.HOME }}/pip.conf'
    PYTHONWARNINGS: 'ignore:Unverified HTTPS request'
...
