---
- name: 'Import PIP role'
  import_role:
    name: 'python/pip'

- name: 'Install Kube-shell (kubernetes integrated shell)'
  pip:
    name: '{{ item.name | default(item) }}'
    version: '{{ item.version | default("omit") }}'
    chdir: ' {{ ansible_env.HOME }}'
    extra_args: '--user'
    state: '{{ item.state | default("present") }}'
    executable: '{{ pip_executable }}'
  environment:
    PIP_CONFIG_FILE: '{{ ansible_env.HOME }}/pip.conf'
    PYTHONWARNINGS: 'ignore:Unverified HTTPS request'
  loop: '{{ kubeshell_dependencies }}'
...
