---
- name: 'Check installed kubetail version'
  shell: '{{ kubetail_install_dir }}/kubetail --version 2>/dev/null'
  args:
    executable: '/bin/bash'
  changed_when: false
  register: 'kubetail_installed_version'

- name: 'Verify installed kubetail version'
  assert:
    that:
      - 'kubetail_version == kubetail_installed_version.stdout'
    fail_msg: 'kubetail installation failed, {{ kubetail_version }} != {{ kubetail_installed_version.stdout }}'
    success_msg: 'Installed kubetail version is: {{ kubetail_version }}'
...
