---
docker_older_packages:
  - 'docker'
  - 'docker-engine'
  - 'docker.io'
  - 'containerd'
  - 'runc'

docker_dependencies:
  - 'apt-transport-https'
  - 'ca-certificates'
  - 'curl'
  - 'gnupg-agent'
  - 'software-properties-common'

docker_download_url: 'https://download.docker.com/{{ ansible_system|lower }}/{{ ansible_distribution|lower }}'
docker_buildx_download_url: "https://github.com/docker/buildx/releases/download/v{{ docker_buildx_version }}/\
                             buildx-v{{ docker_buildx_version }}.{{ docker_os }}-{{ docker_arch }}"
docker_apt_repository: 'deb [arch={{ docker_arch }}] {{ docker_download_url }} {{ ansible_distribution_release }} stable'
...
