---
version: 2.1
jobs:
  execute_tests:
    docker:
      - image: theodore86/vagrantenv-ci):a75bda5
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    resource_class: 'medium'
    steps:
      - 'checkout'
      - run:
          name: 'Run Continuous Integration tests'
          command: 'tox'
workflows:
  on_commit:
    jobs:
      - execute_tests:
          context: 'docker-hub-creds'
          filters:
            branches:
              ignore:
                - 'main'
                - 'create-pull-request/patch'
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - 'main'
    jobs:
      - 'execute_tests'
