---
- name: 'Check installed k9s version'
  shell: '{{ k9s_install_dir }}/k9s version'
  args:
    executable: '/bin/bash'
  changed_when: false
  register: 'k9s_installed_version'

- name: 'Verify installed k9s version'
  assert:
    that:
      - 'k9s_version in k9s_installed_version.stdout'
    fail_msg: 'k9s installation failed, v{{ k9s_version }} != {{ k9s_installed_version }}'
    success_msg: 'Installed k9s version is: v{{ k9s_version }}'
...
