---
docker_arch: 'amd64'
docker_os: '{{ ansible_system | lower }}'
docker_group: 'docker'
docker_pkg_name: "docker-ce"
docker_insecure_registries: []
docker_registries_mirror: []
docker_dns_servers: ['8.8.8.8']
docker_config:
  dns: '{{ docker_dns_servers }}'
  insecure-registries: '{{ docker_insecure_registries }}'
  registry-mirrors: '{{ docker_registries_mirror }}'
  builder:
    gc:
      enabled: true
      policy:
        - keepStorage: 10GB
          filter:
            - unused-for=120h
docker_sdk_install: true
docker_sdk_version: '6.0.1'
docker_sdk_container_name: 'hello-world'
docker_sdk_container_image: '{{ docker_sdk_container_name }}:latest'
docker_compose_install: false
docker_compose_pyyaml_version: '5.4.1'
docker_compose_version: '1.29.2'
docker_buildx_install: true
docker_buildx_version: '0.15.0'
...
