---
- name: 'Get path of user-specific site-packages'
  shell: 'python3 -m site --user-base'
  args:
    executable: '/bin/bash'
  changed_when: false
  register: 'python_userbase'

- name: 'Get installed AWS CLI version'
  shell: '{{ python_userbase.stdout }}/bin/aws --version'
  args:
    executable: '/bin/bash'
  changed_when: false
  register: 'awscli_current_version'

- name: 'Set installed AWS CLI version'
  set_fact:
    awscli_installed_version: |-
      {{ awscli_current_version.stdout | default("") | regex_search(version_re, "\1") | first }}
  vars:
    version_re: 'aws-cli/((?:\d{1,}\.){2}\d{1,})'

- name: 'Verify installed AWS CLI version'
  assert:
    that:
      - 'awscli_installed_version == awscli_package_version'
    fail_msg: 'AWS CLI installation failed: {{ awscli_package_version }} != {{ awscli_installed_version }}'
    success_msg: 'Installed AWS CLI version is: {{ awscli_installed_version }}'
...
