---
- name: 'Setup configuration file'
  template:
    src: 'pip.conf.j2'
    dest: '{{ ansible_env.HOME }}/.pip.conf'
    owner: '{{ ansible_env.USER }}'
    group: '{{ ansible_env.USER }}'
    mode: 0644
  notify:
    - 'Cleanup configuration file'

- name: 'Upgrade, if required'
  pip:
    name: 'pip'
    chdir: '{{ ansible_env.HOME }}'
    state: 'latest'
    executable: '{{ pip_executable }}'
  become: 'yes'
  environment:
    PIP_CONFIG_FILE: '{{ ansible_env.HOME }}/.pip.conf'
    PYTHONWARNINGS: 'ignore:Unverified HTTPS request'
...
