---
- name: 'Check installed kind version'
  shell: '{{ kind_install_dir }}/kind --version'
  args:
    executable: '/bin/bash'
  changed_when: false
  register: 'kind_check_installed_version'

- name: 'Define installed kind version'
  set_fact:
    kind_installed_version: '{{ kind_check_installed_version | default("") | regex_search(version_re) }}'
  vars:
    version_re: '(?:\d{1,}\.){2}\d{1,}'

- name: 'Verify installed kind version'
  assert:
    that:
      - 'kind_installed_version == kind_version'
    fail_msg: 'KIND installation failed, {{ kind_version }} != {{ kind_installed_version }}'
    success_msg: 'Installed KIND version is: {{ kind_version }}'
...
