---
- name: 'Check installed FZF version'
  shell: '{{ fzf_install_dir }}/bin/fzf --version'
  args:
    executable: '/bin/bash'
  changed_when: false
  register: 'fzf_check_installed_version'

- name: 'Define installed FZF version'
  set_fact:
    fzf_installed_version: '{{ fzf_check_installed_version | default("") | regex_search(version_re) }}'
  vars:
    version_re: '(?:\d{1,}\.){2}\d{1,}'

- name: 'Verify installed FZF version'
  assert:
    that:
      - 'fzf_installed_version == fzf_version'
    fail_msg: 'FZF installation failed, {{ fzf_version }} != {{ fzf_installed_version }}'
    success_msg: 'Installed FZF version is: {{ fzf_version }}'
...
