---
- name: 'Install package'
  apt:
    name: '{{ lsyncd_pkg_name }}'
    force_apt_get: 'yes'
    state: 'present'
    install_recommends: 'no'
  become: 'yes'

- name: 'Setup configuration file'
  template:
    src: 'lsyncd.conf.lua.j2'
    dest: '{{ ansible_env.HOME }}/.lsyncd.conf.lua'
    owner: '{{ ansible_env.USER }}'
    group: '{{ ansible_env.USER }}'
    mode: 0644
...
