---
- name: 'Check installed binary version'
  shell: '{{ hadolint_install_dir }}/hadolint --version'
  args:
    executable: '/bin/bash'
  changed_when: false
  register: 'hadolint_installed_version'

- name: 'Set installed binary version'
  set_fact:
    hadolint_existing_version: '{{ hadolint_installed_version | regex_search(version_re) }}'
  vars:
    version_re: '(?:\d{1,}\.){2}\d{1,}'

- name: 'Verify installed binary version'
  assert:
    that:
      - 'hadolint_existing_version == hadolint_version'
    fail_msg: 'Hadolint installation failed, {{ hadolint_version }} != {{ hadolint_existing_version }}'
    success_msg: 'Installed Hadolint with version: {{ hadolint_version }}'
...
