---

groovy_version: '4.0.1'
groovy_checksum: '8ac4a0ccbdc69db3ff17cf20a43dafacc6396f031666f13ff2e7bc6e376e4497'
groovy_install_dir: '/usr/local/groovy'
groovy_distribution_url: 'https://archive.apache.org/dist/groovy/{{ groovy_version }}/distribution'
groovy_binary_url: '{{ groovy_distribution_url }}/apache-groovy-binary-{{ groovy_version }}.zip'
...
