---

tshark_workspace: '/ws'
tshark_version: '3.4.2'
tshark_source: 'wireshark-org-master-ba-3.4.tar.gz'
tshark_build_dir: '/opt/wireshark_e2e'
tshark_reinstall_from_source: false
tshark_group: 'wireshark'

tshark_v2_dependencies:
  - 'automake'
  - 'autoconf'
  - 'byacc'
  - 'flex'
  - 'bison'
  - 'libtool'
  - 'libtool-bin'
  - 'pkg-config'
  - 'libgcrypt11-dev'
  - 'libglib2.0-dev'
  - 'libpcap-dev'
  - 'libcap2-bin'

tshark_v2_build_cmd: |
      ./autogen.sh && ./configure --prefix='{{ tshark_build_dir }}' \
      --enable-tshark \
      --with-krb5=no \
      --with-portaudio=no \
      --with-gnutls=no \
      --with-gcrypt=no \
      --enable-capinfos=no \
      --enable-dumpcap=yes \
      --enable-mergecap=yes \
      --enable-editcap=no \
      --disable-idl2wrs \
      --disable-randpkt \
      --enable-text2pcap=no \
      --enable-androiddump=no \
      --disable-wireshark \
      --disable-warnings-as-errors

tshark_v3_dependencies:
  - 'flex'
  - 'bison'
  - 'cmake'
  - 'build-essential'
  - 'libgcrypt20-dev'
  - 'libglib2.0-dev'
  - 'libpcap-dev'
  - 'libc-ares-dev'
  - 'libnghttp2-dev'
  - 'libcap2-bin'

tshark_v3_build_cmd: 'cmake -DCMAKE_INSTALL_PREFIX="{{ tshark_build_dir }}/" -DBUILD_wireshark=OFF'
...
