---
- name: 'Ensure configuration directory exists'
  file:
    path: '{{ ipython_conf_dir }}'
    state: directory
    owner: '{{ ansible_env.USER }}'
    group: '{{ ansible_env.USER }}'
    mode: 0755

- name: 'Copy IPython configuration file'
  copy:
    src: 'ipython_config'
    dest: '{{ ipython_conf_dir }}/ipython_config.py'
    owner: '{{ ansible_env.USER }}'
    group: '{{ ansible_env.USER }}'
    force: 'yes'
    mode: 0644
...
