---
- name: 'Ensure {{ ansible_env.HOME }}/.gitconfig file exists'
  copy:
    content: ''
    dest: '{{ ansible_env.HOME }}/.gitconfig'
    owner: '{{ ansible_env.USER }}'
    group: '{{ ansible_env.USER }}'
    force: 'no'
    mode: 0644

- name: 'Setup {{ ansible_env.HOME }}/.gitconfig file options'
  template:
    src: 'gitconfig.j2'
    dest: '{{ ansible_env.HOME }}/.gitconfig'
    mode: 0644
    owner: '{{ ansible_env.USER }}'
    group: '{{ ansible_env.USER }}'
...
