---
kubectl_arch: 'amd64'
kubectl_os: '{{ ansible_system | lower }}'
kubectl_base_download_url: 'https://storage.googleapis.com/kubernetes-release/release'
kubectl_download_url: '{{ kubectl_base_download_url }}/v{{ kubectl_version }}/bin/{{ kubectl_os }}/{{ kubectl_arch }}'
kubectl_binary_download_url: '{{ kubectl_download_url}}/kubectl'
kubectl_binary_checksum_download_url: '{{ kubectl_binary_download_url }}.sha512'
...
