---
name: Dockerize

on:
  push:
    branches:
      - 'main'
      - '83-gh-to-automate-the-docker-image-building-for-ci'
    paths:
      - 'Dockerfile'

concurrency:
  group: ${{ github.workflow }}


jobs:
  update_ci_image:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout SCM
        uses: actions/checkout@v3

      - name: Login to docker registry
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          logout: true

      - name: Retrieve latest commit sha as image tag
        id: 'git_short_sha'
        run: |
          short_sha=$(git log -1 --format=%h)
          echo "::set-output name=short_sha::$short_sha"

      - name: 'Update circleCI with the latest image tag'
        run: |
          sudo sed -ri 's|(theodore86/vagrantenv-ci):(.*)|\1:${{ steps.git_short_sha.outputs.short_sha }}|' .circleci/config.yml

      - name: 'Build and push docker image'
        uses: 'docker/build-push-action@v3.0.0'
        with:
          push: true
          context: .
          file: Dockerfile
          no-cache: true
          tags: |
            theodore86/vagrantenv-ci:${{ steps.git_short_sha.outputs.short_sha }}
            theodore86/vagrantenv-ci:latest

      - name: 'Create PR for circleCI workflow having the latest image tag'
        uses: 'peter-evans/create-pull-request@v4'
        with:
          commit-message: 'Update circleCI docker image tag (${{ steps.git_short_sha.outputs.short_sha }})'
          labels: |
              docker
              github action
          add-paths: |
            .circleci/config.yml
...
