---
name: "Issues and PRs Housekeeping"
on:
  schedule:
    - cron: "0 15 * * 1-5"

jobs:
  stale:
    runs-on: 'ubuntu-22.04'
    steps:
      - uses: 'actions/stale@v5.0.0'
        with:
          repo-token: ${{ github.token }}
          stale-pr-message: 'This PR has been marked as stale due to inactivity'
          days-before-stale: 7
          days-before-close: 30
          exempt-pr-labels: 'on-hold'
...
